/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'media',
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'Inter Variable',
          'Inter',
          'Space Grotesk',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Oxygen',
          'Ubuntu',
          'Cantarell',
          'Fira Sans',
          'Droid Sans',
          'Helvetica Neue',
          'sans-serif',
        ],
        serif: [
          'Crimson Pro Variable',
          'Crimson Pro',
          'Georgia',
          'Cambria',
          'Times New Roman',
          'Times',
          'serif',
        ],
        mono: [
          'JetBrains Mono Variable',
          'JetBrains Mono',
          'Fira Code',
          'Monaco',
          'Consolas',
          'Liberation Mono',
          'Courier New',
          'monospace',
        ],
      },
      colors: {
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
          950: '#082f49',
        },
        accent: {
          50: '#fdf4ff',
          100: '#fae8ff',
          200: '#f5d0fe',
          300: '#f0abfc',
          400: '#e879f9',
          500: '#d946ef',
          600: '#c026d3',
          700: '#a21caf',
          800: '#86198f',
          900: '#701a75',
          950: '#4a044e',
        },
        neutral: {
          50: '#fafafa',
          100: '#f5f5f5',
          200: '#e5e5e5',
          300: '#d4d4d4',
          400: '#a3a3a3',
          500: '#737373',
          600: '#525252',
          700: '#404040',
          800: '#262626',
          900: '#171717',
          950: '#0a0a0a',
        },
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.75rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
        '7xl': ['4.5rem', { lineHeight: '1' }],
        '8xl': ['6rem', { lineHeight: '1' }],
        '9xl': ['8rem', { lineHeight: '1' }],
      },
      boxShadow: {
        'soft': '0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 10px 20px -2px rgba(0, 0, 0, 0.04)',
        'medium': '0 4px 25px -5px rgba(0, 0, 0, 0.1), 0 25px 50px -12px rgba(0, 0, 0, 0.25)',
        'hard': '0 10px 40px rgba(0, 0, 0, 0.1)',
        'colored': '0 10px 25px -5px rgba(14, 165, 233, 0.3), 0 8px 10px -6px rgba(14, 165, 233, 0.2)',
        'glow': '0 0 20px rgba(14, 165, 233, 0.3), 0 0 40px rgba(14, 165, 233, 0.1)',
        'inner-soft': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.02)',
      },
      backdropBlur: {
        '4xl': '72px',
      },
      typography: {
        DEFAULT: {
          css: {
            maxWidth: '70ch',
            lineHeight: '1.75',
            fontSize: '1.125rem',
            color: 'rgb(64 64 64)',
            fontFeatureSettings: '"liga" 1, "calt" 1, "kern" 1',
            '--tw-prose-body': 'rgb(64 64 64)',
            '--tw-prose-headings': 'rgb(23 23 23)',
            '--tw-prose-lead': 'rgb(82 82 82)',
            '--tw-prose-links': 'rgb(14 165 233)',
            '--tw-prose-bold': 'rgb(23 23 23)',
            '--tw-prose-counters': 'rgb(115 115 115)',
            '--tw-prose-bullets': 'rgb(212 212 212)',
            '--tw-prose-hr': 'rgb(229 229 229)',
            '--tw-prose-quotes': 'rgb(23 23 23)',
            '--tw-prose-quote-borders': 'rgb(229 229 229)',
            '--tw-prose-captions': 'rgb(115 115 115)',
            '--tw-prose-code': 'rgb(162 28 175)',
            '--tw-prose-pre-code': 'rgb(229 229 229)',
            '--tw-prose-pre-bg': 'rgb(38 38 38)',
            '--tw-prose-th-borders': 'rgb(212 212 212)',
            '--tw-prose-td-borders': 'rgb(229 229 229)',
            '--tw-prose-invert-body': 'rgb(212 212 212)',
            '--tw-prose-invert-headings': 'rgb(250 250 250)',
            '--tw-prose-invert-lead': 'rgb(163 163 163)',
            '--tw-prose-invert-links': 'rgb(56 189 248)',
            '--tw-prose-invert-bold': 'rgb(250 250 250)',
            '--tw-prose-invert-counters': 'rgb(115 115 115)',
            '--tw-prose-invert-bullets': 'rgb(82 82 82)',
            '--tw-prose-invert-hr': 'rgb(64 64 64)',
            '--tw-prose-invert-quotes': 'rgb(250 250 250)',
            '--tw-prose-invert-quote-borders': 'rgb(64 64 64)',
            '--tw-prose-invert-captions': 'rgb(115 115 115)',
            '--tw-prose-invert-code': 'rgb(240 171 252)',
            '--tw-prose-invert-pre-code': 'rgb(212 212 212)',
            '--tw-prose-invert-pre-bg': 'rgb(23 23 23)',
            '--tw-prose-invert-th-borders': 'rgb(82 82 82)',
            '--tw-prose-invert-td-borders': 'rgb(64 64 64)',
            h1: {
              fontSize: 'clamp(2.5rem, 5vw, 3.5rem)',
              fontWeight: '800',
              lineHeight: '1.1',
              marginBottom: '1rem',
              letterSpacing: '-0.025em',
              textWrap: 'balance',
            },
            h2: {
              fontSize: 'clamp(2rem, 4vw, 2.75rem)',
              fontWeight: '700',
              lineHeight: '1.15',
              marginTop: '2rem',
              marginBottom: '1rem',
              letterSpacing: '-0.02em',
              textWrap: 'balance',
            },
            h3: {
              fontSize: 'clamp(1.5rem, 3vw, 2rem)',
              fontWeight: '600',
              lineHeight: '1.25',
              marginTop: '1.75rem',
              marginBottom: '0.75rem',
              letterSpacing: '-0.015em',
            },
            h4: {
              fontSize: 'clamp(1.25rem, 2.5vw, 1.5rem)',
              fontWeight: '600',
              lineHeight: '1.375',
              marginTop: '1.5rem',
              marginBottom: '0.5rem',
            },
            p: {
              marginTop: '1.5rem',
              marginBottom: '1.5rem',
              textWrap: 'pretty',
            },
            a: {
              color: 'rgb(14 165 233)',
              textDecoration: 'none',
              borderBottom: '1px solid rgba(14, 165, 233, 0.3)',
              transition: 'all 0.2s ease',
              '&:hover': {
                borderBottomColor: 'rgb(14 165 233)',
                color: 'rgb(2 132 199)',
              },
            },
            'code::before': {
              content: '""',
            },
            'code::after': {
              content: '""',
            },
            code: {
              background: 'rgba(240, 171, 252, 0.1)',
              padding: '0.125rem 0.375rem',
              borderRadius: '0.375rem',
              fontSize: '0.9em',
              fontWeight: '500',
              border: '1px solid rgba(240, 171, 252, 0.2)',
            },
            pre: {
              borderRadius: '0.75rem',
              border: '1px solid rgb(64 64 64)',
              boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
            },
            blockquote: {
              borderLeftColor: 'rgb(14 165 233)',
              borderLeftWidth: '4px',
              fontStyle: 'italic',
              background: 'rgba(14, 165, 233, 0.05)',
              padding: '1rem 1.5rem',
              borderRadius: '0 0.5rem 0.5rem 0',
            },
            ul: {
              paddingLeft: '1.5rem',
            },
            'ul > li': {
              paddingLeft: '0.5rem',
            },
            'ul > li::marker': {
              color: 'rgb(14 165 233)',
            },
            table: {
              borderRadius: '0.5rem',
              overflow: 'hidden',
              border: '1px solid rgb(229 229 229)',
            },
            th: {
              background: 'rgb(250 250 250)',
              fontWeight: '600',
            },
            'th, td': {
              padding: '0.75rem 1rem',
            },
          },
        },
        sm: {
          css: {
            fontSize: '1rem',
            lineHeight: '1.6',
            p: {
              marginTop: '1.25rem',
              marginBottom: '1.25rem',
            },
            h1: {
              fontSize: 'clamp(2rem, 4vw, 2.5rem)',
              marginBottom: '0.75rem',
            },
            h2: {
              fontSize: 'clamp(1.5rem, 3vw, 2rem)',
              marginTop: '1.5rem',
              marginBottom: '0.75rem',
            },
            h3: {
              fontSize: 'clamp(1.25rem, 2.5vw, 1.5rem)',
              marginTop: '1.25rem',
              marginBottom: '0.5rem',
            },
          },
        },
        lg: {
          css: {
            fontSize: '1.25rem',
            lineHeight: '1.8',
            p: {
              marginTop: '1.75rem',
              marginBottom: '1.75rem',
            },
            h1: {
              fontSize: 'clamp(3rem, 6vw, 4rem)',
              marginBottom: '1.25rem',
            },
            h2: {
              fontSize: 'clamp(2.25rem, 4.5vw, 3rem)',
              marginTop: '2.5rem',
              marginBottom: '1.25rem',
            },
            h3: {
              fontSize: 'clamp(1.75rem, 3.5vw, 2.25rem)',
              marginTop: '2rem',
              marginBottom: '1rem',
            },
          },
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out',
        'fade-in-up': 'fadeInUp 0.6s ease-out',
        'fade-in-down': 'fadeInDown 0.6s ease-out',
        'slide-up': 'slideUp 0.6s ease-out',
        'slide-down': 'slideDown 0.6s ease-out',
        'slide-left': 'slideLeft 0.6s ease-out',
        'slide-right': 'slideRight 0.6s ease-out',
        'scale-in': 'scaleIn 0.4s ease-out',
        'scale-out': 'scaleOut 0.4s ease-out',
        'bounce-in': 'bounceIn 0.8s ease-out',
        'bounce-subtle': 'bounceSubtle 2s infinite',
        'typewriter': 'typewriter 3s steps(40) 1s 1 normal both',
        'blink': 'blink 1s infinite',
        'float': 'float 3s ease-in-out infinite',
        'float-delayed': 'float 3s ease-in-out infinite 1s',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pulse-subtle': 'pulseSubtle 2s ease-in-out infinite',
        'wiggle': 'wiggle 1s ease-in-out infinite',
        'rotate': 'rotate 2s linear infinite',
        'spin-slow': 'spin 3s linear infinite',
        'gradient-x': 'gradientX 3s ease infinite',
        'gradient-y': 'gradientY 3s ease infinite',
        'gradient-xy': 'gradientXY 3s ease infinite',
        'shimmer': 'shimmer 2s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInDown: {
          '0%': { opacity: '0', transform: 'translateY(-20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { transform: 'translateY(30px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-30px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideLeft: {
          '0%': { transform: 'translateX(30px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideRight: {
          '0%': { transform: 'translateX(-30px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        scaleOut: {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '100%': { transform: 'scale(0.9)', opacity: '0' },
        },
        bounceIn: {
          '0%': { transform: 'scale(0.3)', opacity: '0' },
          '50%': { transform: 'scale(1.05)', opacity: '0.8' },
          '70%': { transform: 'scale(0.9)', opacity: '1' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        bounceSubtle: {
          '0%, 20%, 53%, 80%, 100%': { transform: 'translateY(0)' },
          '40%, 43%': { transform: 'translateY(-8px)' },
          '70%': { transform: 'translateY(-4px)' },
          '90%': { transform: 'translateY(-2px)' },
        },
        typewriter: {
          '0%': { width: '0' },
          '100%': { width: '100%' },
        },
        blink: {
          '0%, 50%': { borderColor: 'transparent' },
          '51%, 100%': { borderColor: 'currentColor' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        pulseSubtle: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.8' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        rotate: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        gradientX: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        gradientY: {
          '0%, 100%': { backgroundPosition: '50% 0%' },
          '50%': { backgroundPosition: '50% 100%' },
        },
        gradientXY: {
          '0%, 100%': { backgroundPosition: '0% 0%' },
          '25%': { backgroundPosition: '100% 0%' },
          '50%': { backgroundPosition: '100% 100%' },
          '75%': { backgroundPosition: '0% 100%' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
        glow: {
          '0%': { boxShadow: '0 0 5px currentColor, 0 0 10px currentColor, 0 0 15px currentColor' },
          '100%': { boxShadow: '0 0 10px currentColor, 0 0 20px currentColor, 0 0 30px currentColor' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'gradient-mesh': 'linear-gradient(135deg, var(--tw-gradient-stops))',
        'shimmer': 'linear-gradient(90deg, transparent, rgba(255,255,255,0.2), transparent)',
        'noise': "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 400 400' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)' opacity='0.4'/%3E%3C/svg%3E\")",
      },
      transitionDuration: {
        '250': '250ms',
        '350': '350ms',
        '400': '400ms',
        '450': '450ms',
        '600': '600ms',
        '800': '800ms',
        '900': '900ms',
        '1200': '1200ms',
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
        'bounce': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      blur: {
        '4xl': '72px',
        '5xl': '96px',
      },
      scale: {
        '102': '1.02',
        '103': '1.03',
        '115': '1.15',
      },
    },
  },
  plugins: [],
}